<?xml version="1.0"?>
<package format="3">
  <name>inabot_acs</name>
  <version>0.1.0</version>
  <description>MQTT bridge for FMS using ROS 2</description>
  <maintainer email="you@example.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>fmt</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
