<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sick_safety_controller</name>
  <version>0.0.1</version>
  <description>ROS2 node for interfacing SICK Safety Controller / Flexi Soft with Modbus</description>

  <maintainer email="ysh@example.com">YSH</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>inabot_msgs</depend>

  <!-- 시스템 라이브러리 의존성 (libmodbus) -->
  <build_depend>libmodbus-dev</build_depend>
  <exec_depend>libmodbus-dev</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>